// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Load .env file only in development (Vercel provides env vars directly)
if (process.env.NODE_ENV !== 'production') {
  require('dotenv').config();
}
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed-new.ts",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
